# docker build -t nginx-gunicorn:base -f Dockerfile.base .
FROM        python:3.7.2-slim
MAINTAINER  elonmoon@gmail.com
ENV         LANG    C.UTF-8

RUN         apt-get -y update
RUN         apt-get -y dist-upgrade
RUN         apt-get -y install gcc nginx supervisor && \
            pip3 install gunicorn && \
            apt-get -y remove gcc && \
            apt-get -y autoremove

COPY        requirements.txt /tmp/requirements.txt
RUN         pip3 install -r /tmp/requirements.txt